### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by KonPet** [billbird/gzstat#1]
Hello. I'm I want to implement the DEFLATE compression for a school project. Since I'm not that experienced with reading specification documents yet (and because english isn't my first language), I found the RFC 1951 quite difficult to read, but then I found your lecture on YouTube. It's really helpful and well explained, and you're super fun to listen to. I don't know if my implementation attempt will be successful, but I'm sure that it won't be because of the lack of a good explanation, so I wanted to say thank you. I hope you'll continue uploading your lectures if you ever record any new ones for later courses, since they serve as a great resource for other people as well.

Have a nice day,
Konstantin

PS: Sorry for creating an Issue by the way, I just didn't find any other way to contact you

**Comment by billbird** [comment]
I'm glad to hear that the video was helpful. If you have any questions or want other advice, you can send me an email (bbird at uvic dot ca). I'd be happy to share some of the other materials from the compression course that might be helpful.

**Comment by AltitudeApps** [comment]
Hello, I'm on my RFC 1951 journey as well.  Is there much difference between your Summer 2020 Data Compression lecture, https://www.youtube.com/watch?v=oi2lMBBjQ8s and the Summer 2023 version  https://www.youtube.com/watch?v=SJPvNi4HrWQ ?

I guess I will start with the 2023 version, since I presume that you would have simply re-used the 2020 version if you had been entirely satisfied with it.
